---
- name: Configure kernel parameters.
  sysctl:
    name: '{{ item.variable }}'
    value: '{{ item.value }}'
    state: 'present'
    reload: 'yes'
    sysctl_set: 'yes'
    sysctl_file: '/etc/sysctl.d/20-sysctl.conf'
  loop: "{{ logstash_kernel_parameters|flatten(levels=1) }}"

- name: Creating logstash data folder.
  file:
    dest: '{{ logstash_path }}/logstash'
    state: 'directory'
    owner: 'logstash'
    group: 'logstash'
    mode: '0750'

- name: Creating logstash configuration folder.
  file:
    dest: '/etc/logstash/{{ item }}'
    state: 'directory'
    owner: 'logstash'
    group: 'logstash'
    mode: '0750'
  loop:
    - 'conf.d'
    - 'template'
    - 'patterns'

- name: Geolocation database download.
  unarchive:
    src: "http://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=SdCj43scfhnayMbp&suffix=tar.gz"
    dest: '/etc/logstash'
    owner: 'logstash'
    group: 'logstash'
    mode: '0755'
    extra_opts: [--strip-components=1]
    exclude:
      - 'COPYRIGHT.txt'
      - 'LICENSE.txt'
      - 'README.txt'
    remote_src: 'yes'
    validate_certs: 'no'
  register: logstash_geo_file_download
  until: logstash_geo_file_download is succeeded
  retries: 5
  delay: 2
  changed_when: false
  failed_when: false

- name: Logstash JVM options configuration.
  lineinfile:
    state: present
    dest: '/etc/logstash/jvm.options'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  loop:
    - { regexp: '^-Xms', line: '-Xms{{ logstash_heap_size }}' }
    - { regexp: '^-Xmx', line: '-Xmx{{ logstash_heap_size }}' }
  notify: 'Ensure logstash service is enabled.'

- name: Logstash configuration.
  lineinfile:
    state: present
    dest: '/etc/logstash/logstash.yml'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  loop:
    - { regexp: '^path.data', line: 'path.data: {{ logstash_path }}/logstash' }
    - { regexp: '^pipeline.workers', line: 'pipeline.workers: {{ logstash_arg.pipeline_workers }}' }
    - { regexp: '^pipeline.batch.size', line: 'pipeline.batch.size: {{ logstash_arg.pipeline_batch_size }}' }
    - { regexp: '^pipeline.batch.delay', line: 'pipeline.batch.delay: {{ logstash_arg.pipeline_batch_delay }}' }
    - { regexp: '^http.host', line: 'http.host: {{ ansible_default_ipv4.address }}' }
    - { regexp: '^http.port', line: 'http.port: {{ logstash_port_arg.api }}' }
    - { regexp: '^log.level', line: 'log.level: {{ logstash_port_arg.log_level }}' }
  notify: 'Ensure logstash service is enabled.'

- name: Install Logstash input plugin.
  logstash_plugin:
    state: 'present'
    name: '{{ item }}'
  loop: '{{ logstash_plugins }}'
  register: logstash_plugins_result
  until: logstash_plugins_result is succeeded
  retries: 5
  delay: 2
  no_log: true
  changed_when: false
  failed_when: false
  when: logstash_plugins is defined