---
- name: Logstash exporter program binary transfer.
  unarchive:
    src: 'logstash_exporter.tar.xz'
    dest: '/usr/local/bin'
    owner: 'logstash'
    group: 'logstash'
    mode: '0755'
  notify: 'Ensure logstash exporter service is enabled.'

- name: Logstash exporter configure file transfer.
  template:
    src: 'logstash_exporter.default.j2'
    dest: '/etc/default/logstash_exporter'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Ensure logstash exporter service is enabled.'

- name: Logstash service file transfer.
  copy:
    src: 'logstash_exporter.service'
    dest: '/lib/systemd/system'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Ensure logstash exporter service is enabled.'