---
- name: Gathering service facts.
  service_facts:
  register: services_state

- name: Allow Logstash inputs port.
  firewalld:
    port: "{{ item.port }}/tcp"
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  loop: '{{ logstash_inputs_arg }}'
  changed_when: false
  failed_when: false
  ignore_errors: true
  no_log: true
  when:
    - services_state.ansible_facts.services["firewalld.service"] is defined
    - services_state.ansible_facts.services["firewalld.service"].state == 'running'

- name: Allow Logstash inputs port.
  firewalld:
    port: "{{ item.port }}/udp"
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  loop: '{{ logstash_inputs_arg }}'
  changed_when: false
  failed_when: false
  ignore_errors: true
  no_log: true
  when:
    - services_state.ansible_facts.services["firewalld.service"] is defined
    - services_state.ansible_facts.services["firewalld.service"].state == 'running'

- name: Allow Logstash service port
  firewalld:
    port: '{{ item.value }}/tcp'
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  loop: '{{ logstash_port_arg | dict2items }}'
  when:
    - services_state.ansible_facts.services["firewalld.service"] is defined
    - services_state.ansible_facts.services["firewalld.service"].state == 'running'
