---
- name: Create an index lifecycle policy.
  uri:
    url: '{% if logstash_elastic_stack_auth | bool and logstash_elastic_stack_https | bool %}https{% else %}http{% endif %}://{{ logstash_elastic_hosts[0] }}:{{ logstash_elastic_port }}/_ilm/policy/ilm-history-{{ logstash_rotate_day }}d-policy'
    method: 'PUT'
    user: '{{ logstash_elastic_stack_user }}'
    password: '{{ logstash_elastic_stack_pass }}'
    validate_certs: 'no'
    body: '{"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"set_priority":{"priority":100}}},"delete":{"min_age":"180d","actions":{"delete":{}}}}}}'
    body_format: 'json'
    force_basic_auth: 'yes'
  environment:
    no_proxy: '{{ logstash_elastic_hosts[0] }}'
  register: logstash_ilm_status
  until: logstash_ilm_status.status == 200
  retries: 5
  delay: 2
  changed_when: false
  failed_when: false
  no_log: true
