---
- name: Logstash network input configuration file transfer.
  template:
    src: 'conf/{{ item.name }}.conf.j2'
    dest: '/etc/logstash/conf.d/{{ item.name }}.conf'
    backup: 'yes'
    owner: 'logstash'
    group: 'logstash'
    mode: '0644'
  loop: '{{ logstash_network_inputs_arg }}'
  register: logstash_network_inputs_conf_update

- name: Logstash network input template file transfer.
  template:
    src: 'template/{{ item.name }}.json.j2'
    dest: '/etc/logstash/{{ item.name }}.json'
    backup: 'yes'
    owner: 'logstash'
    group: 'logstash'
    mode: '0644'
  loop: '{{ logstash_network_inputs_arg }}'
  register: logstash_network_inputs_template_update

- name: Logstash network input pattern file transfer.
  copy:
    src: 'pattern/esguardian-{{ item.name }}'
    dest: '/etc/logstash/pattern/esguardian-{{ item.name }}'
    backup: 'yes'
    owner: 'logstash'
    group: 'logstash'
    mode: '0644'
  loop: '{{ logstash_network_inputs_arg }}'
  register: logstash_network_inputs_pattern_update

- name: Logstash blob input configuration file transfer.
  template:
    src: 'conf/{{ item.name }}.conf.j2'
    dest: '/etc/logstash/conf.d/{{ item.name }}.conf'
    backup: 'yes'
    owner: 'logstash'
    group: 'logstash'
    mode: '0644'
  loop: '{{ logstash_blob_inputs_arg }}'
  register: logstash_blob_inputs_conf_update

- name: Logstash blob input template file transfer.
  template:
    src: 'template/{{ item.name }}.json.j2'
    dest: '/etc/logstash/{{ item.name }}.json'
    backup: 'yes'
    owner: 'logstash'
    group: 'logstash'
    mode: '0644'
  loop: '{{ logstash_blob_inputs_arg }}'
  register: logstash_blob_inputs_template_update

- name: Logstash blob input pattern file transfer.
  copy:
    src: 'pattern/esguardian-{{ item.name }}'
    dest: '/etc/logstash/pattern/esguardian-{{ item.name }}'
    backup: 'yes'
    owner: 'logstash'
    group: 'logstash'
    mode: '0644'
  loop: '{{ logstash_blob_inputs_arg }}'
  register: logstash_blob_inputs_pattern_update