---
- name: Logstash input configuration file transfer.
  template:
    src: 'conf/{{ item.name }}.conf.j2'
    dest: '/etc/logstash/conf.d/{{ item.name }}.conf'
    backup: 'yes'
    owner: 'logstash'
    group: 'logstash'
    mode: '0640'
  loop: '{{ logstash_inputs_arg }}'
  register: logstash_inputs_conf_update

- name: Logstash input template file transfer.
  template:
    src: 'template/elastic-{{ item.name }}-template.json.j2'
    dest: '/etc/logstash/template/elastic-{{ item.name }}-template.json'
    backup: 'yes'
    owner: 'logstash'
    group: 'logstash'
    mode: '0640'
  loop: '{{ logstash_inputs_arg }}'
  loop_control:
    index_var: index
  register: logstash_inputs_template_update

- name: Logstash input pattern file transfer.
  copy:
    src: 'pattern/esguardian-{{ item.name }}'
    dest: '/etc/logstash/patterns/esguardian-{{ item.name }}'
    owner: 'logstash'
    group: 'logstash'
    mode: '0640'
  loop: '{{ logstash_inputs_arg }}'
  register: logstash_inputs_pattern_update
