---
- name: Include OS-specific variables.
  include_vars: '{{ ansible_os_family }}.yml'

- name: Add Logstash YUM repositories.
  yum_repository:
    name: '{{ logstash_repo_name }}'
    description: '{{ logstash_repo_name }} YUM repository'
    file: '{{ logstash_repo_name }}'
    baseurl: '{{ logstash_artifacts_repo_url }}'
    gpgcheck: 'no'
    sslverify: 'no'
    timeout: '60'

- name: Install the Logstash dependents packages.
  yum:
    name: '{{ item.package }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  loop: '{{ logstash_dependent_packages }}'
  when: item.create | default(true) | bool
  register: logstash_dependents_status
  until: logstash_dependents_status is succeeded
  retries: 5
  delay: 2

- name: Install the Logstash packages.
  yum:
    name: '{{ logstash_packages }}'
    state: 'present'
    enablerepo: '{{ logstash_repo_name }}'
    validate_certs: 'no'
    update_cache: 'yes'
    disable_gpg_check: 'yes'
  register: logstash_update_status
  until: logstash_update_status is succeeded
  notify: 'Ensure logstash service is enabled.'
  retries: 5
  delay: 2