---
- name: Ensure logstash service is enabled.
  systemd:
    name: 'logstash.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'

- name: Ensure logstash exporter service is enabled.
  systemd:
    name: 'logstash_exporter.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'